name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and Test
      run: xcodebuild clean build test -project FlavorFind.xcodeproj -scheme FlavorFind -destination 'platform=iOS Simulator,name=iPhone Air'
