name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-26
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4
    
    # Cache derived data and other Xcode artifacts
    - name: Cache derived data
      uses: actions/cache@v3
      with:
        path: |
          ~/Library/Developer/Xcode/DerivedData
          ~/Library/Caches/com.apple.dt.Xcode
        key: ${{ runner.os }}-xcode-${{ hashFiles('**/*.pbxproj', '**/*.swift') }}
        restore-keys: |
          ${{ runner.os }}-xcode-

    # Select Xcode version (optional but recommended for consistency)
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.0.app/Contents/Developer

    # Use a valid iPhone simulator name
    - name: Build and Test
      run: |
        xcodebuild clean build test \
          -project FlavorFind.xcodeproj \
          -scheme FlavorFind \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          -configuration Debug \
          -quiet
      timeout-minutes: 25
